domain: evermeet.local
availableUserDomains:
  - .evermeet.local
sitename: ''
plcServer: https://dev-plc.evermeet.app
api:
  enabled: true
  runtime: bun
  adapter: elysia
  host: localhost
  port: 3000
  prefix: /xrpc
  db:
    storage: sqlite
    name: '../../data/evermeet.sqlite'
    connection: mongodb://localhost:27017
    password: putYourPasswordHere
  sessionName: evermeet-session-id
  jwtSecret: Xai9Xahjeisiegeipheogu
web:
  enabled: true
  port: 3001
  host: localhost
featuredCalendars: []