domain: evermeet.local
sitename: null
api:
  enabled: true
  runtime: bun
  adapter: elysia
  host: localhost
  port: 3000
  prefix: /xrpc
  db:
    storage: sqlite
    name: '../../data/evermeet.sqlite'
    connection: mongodb://localhost:27017
    password: putYourPasswordHere
  sessionName: evermeet-session-id
web:
  enabled: true
  port: 3001
  host: localhost
featuredCalendars: []